import { ERank, ESpawnType, GetStructType } from "s2cfgtojson";

export type GearEntries = GetStructType<{
  SpawnType: ESpawnType;
  ItemSID: string;
  SID: string;
  SpawnOnStart: boolean;
  SpawnedPrototypeSID: string;
  ItemGeneratorSettings: {
    PlayerRank: ERank;
    ItemGenerators: { PrototypeSID: string }[];
  }[];
  PackOfItemsPrototypeSID: string;
}>["entries"];

const items = ["Gun", "Armor", "Helmet"];

const attachmentsOrQuestItems = new Set(
  [].concat(
    [
      "TemplateScope",
      "TemplateScopeX2",
      "TemplateScopeX4",
      "TemplateScopeX8",
      "RU_ColimScope_1",
      "EN_ColimScope_1",
      "EN_GoloScope_1",
      "RU_X2Scope_1",
      "EN_X2Scope_1",
      "RU_X4Scope_1",
      "EN_X4Scope_1",
      "RU_X8Scope_1",
      "EN_X8Scope_1",
      "Gauss_Scope",
      "M701_Scope",
      "M701_Colim_Scope",
      "SVDM_Scope",
      "G37_ScopeRail",
      "Gvintar_Scope",
      "SVU_Scope",
      "UDP_Deadeye_Colim",
      "Gun_Silence_ColimScope",
      "Gun_Sledgehummer_GoloScope",
      "Gun_Sotnyk_ColimScope",
      "GunThreeLine_Scope",
      "MuzzleTemplate",
      "DefaultMuzzleTemplate",
      "RU_SinMuz_1",
      "RU_SinMuz_2",
      "RU_SinMuz_3",
      "RU_SinMuz_4",
      "RU_SinMuz_5",
      "RU_AutMuz_1",
      "RU_AutMuz_2",
      "RU_AutMuz_3",
      "EN_SinMuz_1",
      "EN_SinMuz_2",
      "EN_SinMuz_3",
      "EN_SinMuz_4",
      "EN_SinMuz_5",
      "EN_AutMuz_1",
      "EN_AutMuz_2",
      "Zubr_SinMuz",
      "AKU_DefaultMuz",
      "Ram2_SinMuz_1",
      "Mark_DefaultMuz",
      "G37_DefaultMuz",
      "Kharod_DefaultMuz",
      "Fora_DefaultMuz",
      "AK74_DefaultMuz",
      "M16_DefaultMuz",
      "SVDM_DefaultMuz",
      "SVU_DefaultMuz",
      "Gauss_DefaultMuz",
      "Dnipro_DefaultMuz",
      "SilencerTemplate",
      "PistolSilencerTemplate",
      "SMGSilencerTemplate",
      "ARSilencerTemplate",
      "SRSilencerTemplate",
      "RU_Silen_1",
      "RU_Silen_2",
      "RU_Silen_3",
      "EN_Silen_1",
      "EN_Silen_2",
      "EN_Silen_3",
      "EN_Silen_4",
      "Sharpshooter_Silen",
      "Gun_Silence_Silen",
      "Sofmod_Silen",
      "GripTemplate",
      "RU_Grip_1",
      "RU_Grip_2",
      "RU_Grip_3",
      "EN_Grip_1",
      "EN_Grip_2",
      "EN_Grip_3",
      "LaserTemplate",
      "RU_Laser_1",
      "EN_Laser_1",
      "MagTemplate",
      "PairedMagTemplate",
      "BigMagTemplate",
      "HugeMagTemplate",
      "GunPM_MagDefault",
      "GunPM_MagIncreased",
      "GunUDP_MagDefault",
      "GunUDP_MagIncreased",
      "GunM10_MagDefault",
      "GunM10_MagIncreased",
      "Gun_GStreet_MagIncreased",
      "GunAPB_MagDefault",
      "GunAPB_MagIncreased",
      "GunKora_MagDefault",
      "GunKora_MagIncreased",
      "GunNightStalker_MagIncreased",
      "GunViper_MagDefault",
      "GunViper_MagIncreased",
      "Gun_Shakh_MagIncreased",
      "GunAKU_MagDefault",
      "GunAKU_Silence_MagDefault",
      "GunSpitfire_MagDefault",
      "GunAK_MagPaired",
      "GunDrowned_MagPaired",
      "GunBucket_MagDefault",
      "GunBucket_MagIncreased",
      "GunIntegral_MagDefault",
      "GunIntegral_MagIncreased",
      "GunZubr_MagDefault",
      "Gun_RatKiller_MagDefault",
      "GunZubr_MagIncreased",
      "GunAK74_MagDefault",
      "GunAK74_MagIncreased",
      "GunSotnyk_MagDefault",
      "GunM16_MagDefault",
      "GunM16_MagIncreased",
      "GunGP37_MagDefault",
      "GunGP37_MagPaired",
      "GunGP37_MagLarge",
      "GunFora_MagDefault",
      "GunDecider_MagDefault",
      "GunNovator_MagDefault",
      "GunFora_MagIncreased",
      "GunGrim_MagDefault",
      "GunS15_MagDefault",
      "GunGrim_MagIncreased",
      "GunGrim_MagLarge",
      "GunGvintar_MagDefault",
      "GunGvintar_MagIncreased",
      "GunKharod_MagDefault",
      "GunKharod_MagPaired",
      "GunLavina_MagDefault",
      "GunLavina_MagIncreased",
      "GunDnipro_MagDefault",
      "GunDnipro_MagPaired",
      "GunPKP_MagDefault",
      "GunPKP_MagIncreased",
      "GunPKP_MagLarge",
      "GunTank_MagLarge",
      "GunPKP_Korshunov_MagLarge",
      "GunM860_MagLarge",
      "GunD12_MagDefault",
      "GunD12_MagIncreased",
      "GunD12_MagPaired",
      "GunD12_MagLarge",
      "GunSVDM_MagDefault",
      "GunM701_MagDefault",
      "GunMark_MagDefault",
      "GunMark_MagIncreased",
      "GunSVU_MagDefault",
      "GunSVU_MagIncreased",
      "GunGauss_MagDefault",
      "GunGauss_MagIncreased",
      "GunGauss_Scar_MagHuge",
      "RailTemplate",
      "RailPicatiniGP37",
      "TopRailViper",
      "TopRailAKU",
      "TopRailM10",
      "TopRailM860",
      "TopRailSPSA",
      "TopRailD12",
      "TopRailAPB",
      "TopRailRhino",
      "GunBucket_TopRail",
      "GunSVU_ScopeRail",
      "TopRailZubr",
      "GunPM_Screw",
      "TopRailLavina",
      "TopRailLavinaAlternative",
      "TopRailPKP",
      "BottomRailM701",
      "M860LongGrip",
      "M860ShortGrip",
      "G37_BottomRail",
      "TopRailMark",
      "DefaultScopeGrim",
      "TopRailGrim",
      "TopRailKora",
      "MagFedM860",
      "IronsightTemplate",
      "Ironsights_01",
      "Ironsights_02",
      "Ironsights_03",
      "Ironsights_04",
      "G37_IronSight",
      "UnderbarrelTemplate",
      "RU_GLaunch_1",
      "EN_GLaunch_1",
      "EN_BuckLaunch_1",
      "GunGrim_GLaunch",
      "GunIntegral_FrontExtension",

      "Gun_Partner_SR",
      "Gun_Sotnyk_AR_GS",
      "GunNightStalker_HG",
      "Gun_ProjectY_HG",
      "Gun_Deadeye_HG",
      "Gun_Krivenko_HG",
      "Gun_Star_HG",
      "Gun_Encourage_HG",
      "Gun_GStreet_HG",
      "Gun_Shakh_SMG",
      "Gun_Spitter_SMG",
      "Gun_Silence_SMG",
      "Gun_RatKiller_SMG",
      "Gun_Spitfire_SMG",
      "Gun_Combatant_AR",
      "Gun_Drowned_AR",
      "Gun_Lummox_AR",
      "Gun_Decider_AR",
      "Gun_Merc_AR",
      "Gun_Sotnyk_AR",
      "Gun_Sharpshooter_AR",
      "Gun_Unknown_AR",
      "Gun_Trophy_AR",
      "Gun_SOFMOD_AR",
      "Gun_S15_AR",
      "Gun_Predator_SG",
      "Gun_Sledgehammer_SG",
      "Gun_Texas_SG",
      "Gun_Tank_MG",
      "Gun_Lynx_SR",
      "Gun_Partner_SR",
      "Gun_Whip_SR",
      "Gun_Cavalier_SR",
      "Gun_SkifGun_HG",
      "GunSVU_Sniper_Duga_SP",
      "GunGauss_Scar_SP",
      "GunGauss_Scar_SP",
      "GunNightStalker_HG",
      "GunUDP_Deadeye_HG",
      "Gun_Krivenko_HG_GS",
      "Gun_S15_AR",
      "Gun_Sharpshooter_AR_GS",
      "Gun_Cavalier_SR_GS",
      "Gun_Unknown_AR_GS",
      "Gun_GStreet_HG_GS",
      "Gun_Encourage_HG_GS",
      "Gun_Star_HG_GS",
      "Gun_Shakh_SMG_GS",
      "Gun_RatKiller_SMG_GS",
      "Gun_Silence_SMG_GS",
      "Gun_Spitter_SMG_GS",
      "Gun_Spitfire_SMG_GS",
      "Gun_Lynx_SR_GS",
      "Gun_Whip_SR_GS",
      "Gun_Partner_SR_GS",
      "Gun_SOFMOD_AR_GS",
      "Gun_Predator_SG_GS",
      "Gun_Sledgehammer_SG_GS",
      "Gun_Texas_SG_GS",
      "Gun_Combatant_AR_GS",
      "Gun_Drowned_AR_GS",
      "Gun_Lummox_AR_GS",
      "Gun_Merc_AR_GS",
      "Gun_Tank_MG_GS",
      "Gun_Sotnyk_AR_GS",
      "Gun_Trophy_AR_GS",
      "Gun_Decider_AR_GS",
      "Gun_Kaimanov_HG_GS",
      "GunTOZ_Gonta",
    ], // quest/unique items
  ),
);

export const meta = {
  interestingFiles: ["WorldMap_WP"],
  interestingContents: ["ESpawnType::Item", ...items],
  prohibitedIds: [],
  interestingIds: [],
  description: `
    This mode does only one thing: removes all 436 weapons / armors placed around the Zone[hr][/hr]
Full scavenger mode! 
    `,
  changenote: "Update for 1.6",
  entriesTransformer: (entries: GearEntries) => {
    if (entries.SpawnType === "ESpawnType::Item") {
      const isGearReplacement = items.some((i) => entries.ItemSID?.includes(i)) && !attachmentsOrQuestItems.has(entries.ItemSID);
      if (isGearReplacement) {
        console.info(`Found preplaced item: ${entries.ItemSID}. Hiding it.`);
        const res: Partial<GearEntries> = {
          SpawnOnStart: false,
          SpawnType: entries.SpawnType,
          SID: entries.SID,
        };

        if (entries.ItemSID) res.ItemSID = entries.ItemSID;

        return res as GearEntries;
      }
    }
    return null;
  },
};
